### PR TITLE
Fixed bug when typing "s" or "d" + "any character"

### LINKED ISSUE #40: Bug when typing "s"/"d" with another character in rapid succession
Steps to reproduce: Type "s" or "d" followed by another character in rapid succession (`< MAX_TIME_BETWEEN_SIMULTANEOUS_KEY_PRESSES`), such as `se` really fast. Instead of inserting `se`, `es` is inserted.
Running on macOS 10.13.5 with Hammerspoon 0.9.66. This issue has been consistently reproduced with Hammerspoon running, and has been consistently absent with Hammerspoon closed.

### PR DESCRIPTION
**Pull request by denosawr**
Fixes #40. This commit seems to consistently fix the issue.

### CODE REVIEW

**Comment by jasonrudolph** [comment]
:wave: Hi @denosawr: I tried out these changes, but they don't seem to fix the issue for me. Here's the behavior I'm seeing:

1. Set [timeout](https://github.com/jasonrudolph/keyboard/blob/bd2f8ff879010f454b7ed642015eccae2767c90d/hammerspoon/super.lua#L8) to 200 ms and reload Hammerspoon config
2. In rapid succession:
    1. Press `s`
    2. Release `s`
    3. Press `e`
    4. Release `e`
3. Observe that `es` is typed

Does this match the behavior you're seeing?

In order to consider #40 to be fixed, I think we need to see `se` get typed. Right?

---

Software Versions:

- macOS 10.13.6
- Hammerspoon 0.97.0

**Comment by denosawr** [comment]
Huh, that's weird. It _does_ match the behaviour I'm seeing on timeout 0.2 (200ms). However, if you set timeout back to 0.04 (40ms, default), you'll find that it definitely works.

macOS 10.13.5 and Hammerspoon 0.9.7 here.

**Comment by denosawr** [comment]
Hm, can you still reproduce this? I can't seem to repro it...

**Comment by jasonrudolph** [comment]
> Hm, can you still reproduce this? 

@denosawr: Yes. I just checked out this branch again and tried out  the steps in https://github.com/jasonrudolph/keyboard/pull/41#issuecomment-406087831, and I can still reproduce that behavior. (I'm using Hammerspoon 0.9.73 on macOS 10.14.3.)

**Comment by denosawr** [comment]
Uh... that wasn't meant to happen... my bad. I'll just make a new PR, I guess.

**Pull request closed without merging**
