### PR TITLE
macOS Sierra Support

### PR DESCRIPTION
**Pull request by jasonrudolph**
This setup has historically relied heavily on [Karabiner](https://pqrs.org/osx/karabiner/). According to [the Karabiner site](https://github.com/tekezo/pqrs.org/blob/4d294ef1e321708db840951826d2d737ae5c0b5d/source/page/osx/karabiner/index.mustache#L64-L73):

> Karabiner does not work on macOS Sierra at the moment.
>
> We are developing [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) which provides simple key modification for macOS Sierra at first. (Karabiner-Elements works well on macOS Sierra. We are working on fixing several remaining issues.)
>
> We'll start updating for the full featured Karabiner for Sierra after Karabiner-Elements is completed.

I have high hopes for all a full-featured Karabiner coming to Sierra 🤞, but in the meantime, I'd :heart: to have as much of this setup working on Sierra as possible.

This branch represents a work-in-progress attempt to port the majority of this repository's [pre-Sierra functionality](https://github.com/jasonrudolph/keyboard/blob/e19948b26cc569e41637d60a5357d1d2e46669eb/README.md#more-useful-for-me) to Sierra. Presently, the tools available on Sierra lack the power and flexibility available in Karabiner. Given those limitations, porting the previous functionality to Sierra will likely involve compromises. It's unlikely to be an exact port.

### TODO

- [x] A more useful caps lock
    - [x] Tap **caps lock** for **escape**
    - [x] Hold **caps lock** for **control**
- [x] Enable navigation via the home row ([See README 📝](https://github.com/jasonrudolph/keyboard/blob/sierra/README.md#super-duper-mode))
    - [x] Left/down/up/right
    - [x] Previous/next word
        - [x] In most apps
        - [x] In iTerm2
    - [x] Start/end of line
    - [x] Page down/up
    - [x] Select while navigating
    - [x] Delete previous/next word
    - [x] Delete to start/end of line
- [x] Enable other commonly-used actions on or near the home row ([See README 📝](https://github.com/jasonrudolph/keyboard/blob/sierra/README.md#miscellaneous-goodness))
    - [x] Previous/next tab
    - [x] First/last tab
    - [x] Split panes horizontally/vertically in iTerm2
    - [x] Move left/up/down/right by one pane in iTerm2
- [x] Window management using keyboard shortcuts on or near the home row
    - [x] Send window left (left half of screen) - **control** + **s**, **h**
    - [x] Send window down (bottom half of screen) - **control** + **s**, **j**
    - [x] Send window up (top half of screen) - **control** + **s**, **k**
    - [x] Send window right (right half of screen) - **control** + **s**, **l**
    - [x] Send window to upper left - **control** + **s**, **i**
    - [x] Send window to upper right - **control** + **s**, **o**
    - [x] Send window to lower left - **control** + **s**, **,**
    - [x] Send window to lower right - **control** + **s**, **.**
    - [x] Send window to center of screen - **control** + **s**, **space**
    - [x] Resize window to fill the screen - **control** + **s**, **enter**
    - [x] Send window to next monitor - **control** + **s**, **n**
- [x] Hyper key for quickly launching apps
    - [x] Use **right option** key as **hyper** key
    - [x] **hyper** + **a** to open iTunes ("A" for "Apple Music")
    - [x] **hyper** + **b** to open Google Chrome ("B" for "Browser")
    - [x] **hyper** + **c** to open Hackable Slack Client ("C for "Chat")
    - [x] **hyper** + **d** to open Remember The Milk ("D" for "Do!" ... or "Done!")
    - [x] **hyper** + **e** to open Atom Beta ("E" for "Editor")
    - [x] **hyper** + **f** to open Finder ("F" for "Finder")
    - [x] **hyper** + **g** to open Mailplane 3 ("G" for "Gmail")
    - [x] **hyper** + **t** to open iTerm ("T" for "Terminal")
- [x] [Markdown formatting](https://github.com/jasonrudolph/keyboard/blob/sierra/README.md#markdown-mode)
    - [x] Italics (Wrap the currently-selected text in single asterisks) - **control** + **m**, **i**
    - [x] Bold (Wrap the currently-selected text in double asterisks) - **control** + **m**, **b**
    - [x] Strikethrough (Wrap the currently-selected text in double tildes - **control** + **m**, **s**
    - [x] Inline link (Convert the currently-selected text to an inline link, using a URL from the clipboard) - **control** + **m**, **l**
- [x] Consider providing visual indicator when in (S)uper (D)uper Mode, WindowLayout Mode, and Markdown Mode
- [x] Update README

### CODE REVIEW

**Comment by jasonrudolph** [comment]
3fb5e77f7c5e6b5d7cb3e247ac016016d17ea096 adds support for "(S)uper (D)uper Mode" on macOS Sierra. Most of the [pre-Sierra features](https://github.com/jasonrudolph/keyboard/blob/e19948b26cc569e41637d60a5357d1d2e46669eb/screenshots/karabiner-change-key-config-02.png) are available:

>	**(S)uper (D)uper Mode**
>
> To activate, push the **s** and **d** keys simultaneously and hold them down. Now you're in (S)uper (D)uper mode. It's like a secret keyboard _inside_ your keyboard. (Whoa.) It's optimized for keeping you on the home row, or very close to it. Now you can:
>
> - Use **h**/**j**/**k**/**l** for **up**/**down**/**left**/**right** respectively
> - Use **a** for **alt** (AKA **option**)
> - Use **f** for **command**
> - Use **space** for **shift**
> - Use **a** + **j**/**k** for **page up**/**page down**
> - Use **i**/**o** to move to the previous/next tab
> - Use **a** + **h**/**l** to move to previous/next word in most apps (but not yet in iTerm2)

Prior to Sierra, this functionality :point_up: relied on Karabiner's [Simultaneous VI Mode](https://github.com/tekezo/Karabiner/blob/8fe38da09ff0f05e20e0f4cde80258435bfcad47/src/core/server/Resources/include/checkbox/simultaneouskeypresses_vi_mode.xml). Since [Karabiner-Elements doesn't yet support Simultaneous VI Mode](https://github.com/tekezo/Karabiner-Elements/issues/153), this pull request implements the functionality via Hammerspoon.

---

/fyi @pengwynn @adamyonk @spicycode: This might be of interest to you. ⌨️ :neckbeard:

**Comment by adamyonk** [comment]
This is looking great! I hand't played with Hammerspoon before - the possibilities are exciting.

I'm having trouble getting the window movements to work - It looks like `CAPS+W` is getting overwritten somehow. If I reload and open up the console and hit `CAPS+W+H` or `CAPS+W+L` it seems like it just sends `⌃+H` or `⌃+L`.

```
10:16:45     hotkey: Disabled hotkey F20
10:16:46 betterCaps:     Sending keystroke: {ctrl} l
10:16:47                 Sending keystroke: {ctrl} h
10:16:49     hotkey: Enabled hotkey F20
```

(This is me hitting `CAPS+W+H, L`)

Let me know if I can be of more help troubleshooting that.

**Comment by jasonrudolph** [comment]
> I'm having trouble getting the window movements to work

@adamyonk: I think this might be a quirk of the implementation and/or poor documentation on my part. 😬 

With the current implementation, you need to:

1. Press caps lock + w
2. Release caps lock + w
3. Press the desired window movement key (e.g., h)

That _should_ do the trick. With that flow, you should see something like this in the Hammerspoon console:

```
13:10:17     hotkey: Disabled hotkey F20
             hotkey: Disabled hotkey F16
             hotkey: Enabled hotkey F20
             hotkey: Enabled hotkey F16
```

Based on the console output you showed, I'm _guessing_ that you're not performing step 2. (Again, this is likely due to me not yet providing sufficient docs. 🙈 ) Could this explain the behavior you're seeing?

**Comment by jasonrudolph** [comment]
@adamyonk: Oh, and thank you for trying this out. :bow:⚡️ 

I definitely welcome and appreciate your feedback. Let me know if https://github.com/jasonrudolph/keyboard/pull/10#issuecomment-268036995 doesn't explain things, and please let me know if you run into any other issues or things that you think could be better. 💟

**Comment by adamyonk** [comment]
@jasonrudolph that was it, I just misunderstood, thanks!

The only other thing is that I keep adding keys to [this array](https://github.com/jasonrudolph/keyboard/pull/10/files#diff-8414589559482974f12f5c42ef927ca8R64). Would be nice if it could be structured to make any key get piped through there unless it was blocked by some other function.

**Comment by adamyonk** [comment]
Along the same lines, I have some shortcuts like `⌃+⌘+/` - I could add `/` to the keys array, but anything starting with ⌃ looks like it ignores any other meta keys. I think there's probably a more passive hotkey setup that would allow that to pass through, but I've yet to dig into Hammerspoon enough to understand it yet. 🤓

**Comment by adamyonk** [comment]
I really love this setup though, I could see this being _more_ configurable than what we could do previously with Karabiner, and that's awesome!

**Comment by jasonrudolph** [comment]
> The only other thing is that I keep adding keys to [this array](https://github.com/jasonrudolph/keyboard/pull/10/files#diff-8414589559482974f12f5c42ef927ca8R64). Would be nice if it could be structured to make any key get piped through there unless it was blocked by some other function.
>
> Along the same lines, I have some shortcuts like `⌃+⌘+/` - I could add `/` to the keys array, but anything starting with ⌃ looks like it ignores any other meta keys. I think there's probably a more passive hotkey setup that would allow that to pass through, ...

@adamyonk: Thanks for this feedback. I'm adding this to the task list in the pull request body. :bow:

**Comment by jasonrudolph** [comment]
> - [x] Window management using keyboard shortcuts on or near the home row

This branch now includes [an initial implementation of all of the window management features](https://github.com/jasonrudolph/keyboard/blob/8027effe1ed2c614ebc58ae377ca901c711978d5/hammerspoon/better-caps-lock.lua#L95-L111), including [sending the current window to any of the four corners](https://github.com/jasonrudolph/keyboard/blob/8027effe1ed2c614ebc58ae377ca901c711978d5/hammerspoon/better-caps-lock.lua#L105-L108) and [sending the current window to the next monitor](https://github.com/jasonrudolph/keyboard/blob/8027effe1ed2c614ebc58ae377ca901c711978d5/hammerspoon/better-caps-lock.lua#L110).

I'm not yet using this branch full-time, so it's too soon to say whether this implementation will feel natural when used on a daily basis. In other words: buyer beware and feedback welcome. 😇

**Comment by jasonrudolph** [comment]
> The only other thing is that I keep adding keys to [this array](https://github.com/jasonrudolph/keyboard/pull/10/files#diff-8414589559482974f12f5c42ef927ca8R64). Would be nice if it could be structured to make any key get piped through there unless it was blocked by some other function.
>
> Along the same lines, I have some shortcuts like `⌃+⌘+/` - I could add `/` to the keys array, but anything starting with ⌃ looks like it ignores any other meta keys. I think there's probably a more passive hotkey setup that would allow that to pass through, ...

@adamyonk: With the changes in https://github.com/jasonrudolph/keyboard/compare/e09a40e3362e0c370d90b60bb4080d4757c0dc6d...9f70290e3a27637e1b5c2d83e8108c0c3998d904, holding caps lock should be equivalent to holding control in all scenarios. :sweat_smile:

**Comment by adamyonk** [comment]
@jasonrudolph so awesome! Just updated my setup with the latest here. I'll report back if I see any issues this week!

**Comment by jasonrudolph** [comment]
A few updates:

- [Markdown Mode](https://github.com/jasonrudolph/keyboard/blob/d89e4f98dc66e94758a947d6125dd3166d1e05e0/hammerspoon/markdown.lua#L51-L64) is now implemented
- In iTerm2, **control** + **dash**/**pipe** splits panes horizontally/vertically (46d0efdf199d1a81e7f020ae6ea62ce9ef024048)
- In iTerm2, **control** + **h**/**j**/**k**/**l** moves left/down/up/right by one pane (https://github.com/jasonrudolph/keyboard/pull/10/commits/89e8bb4c7940d115a5d3e0f6314af43dc199706e)
- [WindowLayout Mode](https://github.com/jasonrudolph/keyboard/blob/d89e4f98dc66e94758a947d6125dd3166d1e05e0/hammerspoon/windows.lua#L170-L186) is now bound to **control**+**s** instead of **control**+**w** (for [reasons](https://github.com/jasonrudolph/keyboard/pull/10/commits/d89e4f98dc66e94758a947d6125dd3166d1e05e0))

**Comment by adamyonk** [comment]
Did my Monday `sierra` branch update this morning. So far, so good! The escape key delay workaround is awesome. Using ⌃+h/j/k/l is a pretty common movement to get around vim and tmux splits, for those that use them, so encapsulating your code for navigating iTerm splits into `panes.lua` is much appreciated! I just had to comment out that require in the `init.lua` and I was off to the races. Stellar work on this!

**Comment by jasonrudolph** [comment]
> I'm not yet using this branch full-time, so it's too soon to say whether this implementation will feel natural when used on a daily basis. -- https://github.com/jasonrudolph/keyboard/pull/10#issuecomment-269928192

**Update**: I've started using this branch full-time, with *mostly* positive results. So far, I'm only noticing one issue:

[(S)uper (D)uper mode](https://github.com/jasonrudolph/keyboard/blob/c895198f2f275df5fed3facfb426021a3847996e/README.md#sierra-port) occasionally fails to trigger some actions. For example, if I [hit `i` to move to the previous tab](https://github.com/jasonrudolph/keyboard/blob/c895198f2f275df5fed3facfb426021a3847996e/hammerspoon/super.lua#L143-L164), it *usually* works, but sometimes it doesn't. 🤔 In the Hammerspoon console, the [log shows](https://github.com/jasonrudolph/keyboard/blob/cee11c7d2bb2b57449bbdd62abf261a988b04d6a/hammerspoon/init.lua#L9) that we [triggered the `command+shift+[` keystroke](https://github.com/jasonrudolph/keyboard/blob/c895198f2f275df5fed3facfb426021a3847996e/hammerspoon/super.lua#L154) to move to the previous tab, but the app (Chrome, Finder, Atom, etc.) doesn't actually move to the previous tab. If I try again, it works. @adamyonk: Have you observed this issue? Have you noticed any other issues?

I'll continue using this branch for the rest of this week. If things go smoothly, I'll move on to updating the README, and then I'll merge this branch.

**Comment by adamyonk** [comment]
Pulled down the latest this morning, it's working great! I especially like the super duper and window layout mode notifications. Regarding your tab-switching bugginess comment, I noticed that switching tabs would get tripped up for me if the tab I switched to had focus on an input when I left it - that input would start capturing everything instead of continuing to move between tabs. I'm not sure if there would even be a way to keep that from happening, but I wonder if that was why it was happening for you? Anyway, it is working splendidly for me - awesome work!

**Comment by jasonrudolph** [comment]
@adamyonk: Thanks for all your testing and feedback this pull request. Your enthusiasm and support made this even more fun! 🍻 If you notice any issues or have any feedback, I'm all ears. 💟

**Comment by jasonrudolph** [comment]
Now that this pull request is merged, if anyone is looking for the pre-Sierra bits, the [v1.0.0 release](https://github.com/jasonrudolph/keyboard/releases/tag/v1.0.0) is suitable for use on OS X El Capitan (10.11), and it probably works on OS X Yosemite (10.10) and OS X Mavericks (10.9) as well.

The changes in this pull request (which are present in the new [v2.0.0 release](https://github.com/jasonrudolph/keyboard/releases/tag/v2.0.0)), are suitable for use on macOS Sierra (10.12) and OS X El Capitan (10.11).

:v:

**Comment by gvaughn** [comment]
I'm over a month late, but a big :thumbsup: and thank you @jasonrudolph. I currently rely on parts of this in El Capitan and have delayed upgrading to Sierra because of it. Now I have a clear path. Much appreciated.

**Comment by duff** [comment]
I'm really digging the project too!

**Comment by narze** [comment]
Wow. Just found this just after I go all the way to solve it in [hardware level]( https://github.com/narze/qmk_firmware/tree/master/keyboards/planck/keymaps/narze)! 🙈 
Now I can get back to use my Macbook's keyboard now. Thank you! 😆

**Pull request merged**
